blueprint:
  name: Filament Inventory
  description: Automation to decrement stock or notify stock info depending on scanner
  domain: automation
  input:
    inventory_id_number:
      name: Inventory ID
      description: Select Simple Inventory ID used for Filament
      selector:
        entity:
          filter:
            - integration: simple_inventory
    notify_device:
      name: Notify Device
      description: Select which device you want to send notifications to
      selector:
        device:
          integration: mobile_app

variables:
  input_inventory_id_number: !input 'inventory_id_number'
  input_inventory_id_number_id: "{{ state_attr(input_inventory_id_number,'inventory_id') }}"
  scanned_tag: "{{ trigger.event.data.tag_id }}"
  scanned_name: "{{ trigger.event.data.name }}"
  inventory_name: >
    {% for item in state_attr('sensor.filament_inventory','items') %}
      {{ item.name }}
    {% endfor %}
  input_notify_device: !input 'notify_device'

triggers:
  - platform: event
    event_type: tag_scanned

condition:
  - condition: template
    value_template: "{{ scanned_name in inventory_name }}"

actions:
  - device_id: !input 'notify_device'
    domain: mobile_app
    type: notify
    title: "Filament Action"
    message: "Choose what to do with {{ trigger.event.data.name }}"
    data:
      actions:
        - action: "DECREMENT"
          title: "Decrement"
        - action: "SHOW_INFO"
          title: "Show Info"

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: DECREMENT
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: SHOW_INFO
    timeout: "00:05:00"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == 'DECREMENT' }}"
        sequence:
          - service: simple_inventory.decrement_item
            data:
              inventory_id: "{{ state_attr('sensor.filament_inventory','inventory_id') }}"
              name: "{{ trigger.event.data.name }}"
              amount: 1

      - conditions:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == 'SHOW_INFO' }}"
        sequence:
          - device_id: !input 'notify_device'
            domain: mobile_app
            type: notify
            title: "Filament Info"
            message: >
              {% set test = trigger.event.data.name %}
              {% for item in state_attr('sensor.filament_inventory', 'items') %}
                {% if item.name == test %}
                  {% if item.category == "" %}
                    {{ item.name }}
                  {% else %}
                    {{ ([item.name] + state_attr('input_select.' ~ (item.category | replace(' ', '_')), 'options')) | join('\n') }}
                  {% endif %}
                {% endif %}
              {% endfor %}

